local_backend: true
backend:
  name: git-gateway
  branch: master
  squash_merges: true
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/collections/posts
    create: true
    fields:
      - name: title
        label: Title
      - name: section
        label: Section
        hint: This will decide which section the post appears in on the homepage and article collection pages.
        widget: select
        options:
          - { label: 'Announcements', value: 'announcements' }
          - { label: 'Articles', value: 'articles' }
          - { label: 'Speciality', value: 'speciality' }
      - name: category
        label: Category
        hint: This will determine what label will show above the post title.
        widget: select
        options:
          - { label: 'None', value: '' }
          - { label: 'Announcement', value: 'announcement' }
          - { label: 'News', value: 'news' }
          - { label: 'Guide', value: 'guide' }
          - { label: 'Interview', value: 'interview' }
          - { label: 'Event', value: 'event' }
      - name: publish
        label: Publish Date
        widget: datetime
      - name: lastUpdated
        label: Last Updated
        widget: datetime
        required: false
      - name: homepageText
        label: Homepage Text
        required: false
        hint: This text is used when displaying this post as a component of the homepage. If not provided, the title will be used.
      - name: body
        label: Body
        widget: markdown
        modes:
          - raw
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/posts
        choose_url: false
      - name: authors
        label: Author(s)
        widget: relation
        multiple: true
        collection: people
        search_fields: [name]
        value_field: '{{beatsaverId}}'
        display_fields: [name]
        required: false
        hint: The author(s) of this article. You can select multiple, but you don't have to specify any!
      - name: credits
        label: Credits
        required: false
        widget: list
        summary: 'Thanks to {{fields.contributor}} for {{fields.contribution}}.'
        fields:
          - name: contributors
            label: Contributor(s)
            widget: relation
            collection: people
            search_fields: [name]
            value_field: '{{beatsaverId}}'
            display_fields: [name]
            multiple: true
            hint: The contributor(s) of this article. You can select multiple if they have contributed in the same way.
          - name: contribution
            label: Contribution
            widget: string
            hint: 'The contribution of the contributor(s) to this article. If provided it will be inserted into the articles as "Thanks to {{Contributor}} for {{Contribution}}." If not provided, {{Contribution}} will default to "for their contribution". Example: ''the feedback and proofreading the article''.'
            required: false
      - name: showInPostListing
        label: Show in post listing
        widget: boolean
        default: true
      - name: linkToSpecialtyPage
        label: Link to Specialty Page
        required: false
        hint: "If there is a specialty page for this post, provide the URL here. This is used to link it as canonical URL in the metadata (SEO). Only provide the path, not the full URL. Do: /speciality/your-speciality-page, Don't: https://bsaber.com/speciality/your-speciality-page"
        widget: string
  - name: map-of-the-week
    label: Map of the Week
    folder: src/collections/map-of-the-week
    slug: '{{startDate}}'
    create: true
    editor:
      preview: false
    fields:
      - name: mapId
        label: Map  ID
        hint: The BeatSaver ID of the map of the week. You can find this one in the URL of the map's page on beatsaver.com. For example, the ID of the map https://beatsaver.com/maps/8f is the last part 8f.
      - name: review
        label: Review
        hint: 'An accompanying text to the map of the week that should review and ideally describe what made it the MOTW. Example "This map has a fantastic lightshow on the new Lattice environment, a poodle diff and three other diffs accessible to a variety of players with great and unique usage of arcs."'
        widget: text
      - name: startDate
        label: Start Date
        hint: Starting when the map of the week should be displayed on the root page.
        default: '{{now}}'
        widget: datetime
        picker_utc: true
      - name: showcase
        label: Showcase
        hint: "A video that will be embedded in a modal on the map of the week page. This should be a video that showcases the map in a good way. If you don't have a video, you can leave this empty."
        required: false
        widget: object
        fields:
          - name: id
            label: ID
            hint: The ID of the video. For YouTube videos and shorts, this is the last part of the URL. For example, the ID of the video https://www.youtube.com/shorts/ed8A3n49Gmg is the last part ed8A3n49Gmg.
            widget: string
            required: false
          - name: type
            label: ID Type
            widget: select
            required: false
            options:
              - { label: 'YouTube Short', value: 'youtube-short' }
              - { label: 'YouTube Video', value: 'youtube-video' }
      - name: coverUrlOverwrite
        label: Cover URL
        required: false
        hint: If you want to use a different cover image than the one fetched from BeatLeader, you can provide a URL here.
        widget: string
  - name: community-labels
    label: Community Labels
    folder: src/collections/community-labels
    slug: '{{label}}'
    create: true
    fields:
      - name: label
        label: Label
        widget: string
      - name: description
        label: Description
        widget: string
      - name: color
        label: Color
        widget: color
  - name: community
    label: Community
    folder: src/collections/communities
    slug: '{{name}}'
    create: true
    fields:
      - name: name
        label: Name
      - name: description
        label: Description
        widget: text
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/communities
        choose_url: false
      - name: circleFrameImage
        label: Circle Frame Image
        widget: boolean
        required: true
        hint: If enabled, the image will be circularly cut. Some logos have transparenct background and look better without doing so while - for example ScoreSaber, Beat Saber League Japan, Acc Community look better without the circle frame cutout.
        default: true
      - name: labels
        label: Labels
        widget: relation
        collection: community-labels
        multiple: true
        max: 2
        search_fields: [label]
        value_field: label
        display_fields: [label]
      - name: activityLevel
        label: Activity Level
        widget: select
        options:
          - { label: 'Low', value: 'low' }
          - { label: 'Medium', value: 'medium' }
          - { label: 'High', value: 'high' }
      - name: socials
        label: Socials
        widget: list
        multiple: true
        fields:
          - {
              label: Name,
              name: name,
              widget: select,
              options:
                [
                  'Discord',
                  'Twitter/X',
                  'Facebook',
                  'Instagram',
                  'Twitch',
                  'YouTube',
                  'Reddit',
                  'GitHub',
                  'Website',
                  'Documentation',
                ],
            }
          - { label: URL, name: url, widget: string }
          - {
              label: Title Overwrite,
              name: titleOverwrite,
              widget: string,
              hint: The title is the text that appears if you hover over the icon. If you want to overwrite it,
              you can do so here. Otherwise,
              the title will be the same as the name that has been selected.,
              required: false,
            }
      - name: languages
        label: Languages
        widget: select
        multiple: true
        options:
          - { label: 'English', value: 'en' }
          - { label: 'German', value: 'de' }
          - { label: 'French', value: 'fr' }
          - { label: 'Spanish', value: 'es' }
          - { label: 'Italian', value: 'it' }
          - { label: 'Japanese', value: 'ja' }
          - { label: 'Korean', value: 'ko' }
          - { label: 'Dutch', value: 'nl' }
          - { label: 'Polish', value: 'pl' }
          - { label: 'Portuguese', value: 'pt' }
          - { label: 'Russian', value: 'ru' }
          - { label: 'Chinese', value: 'zh' }
          - { label: 'Swedish', value: 'sv' }
          - { label: 'Norwegian', value: 'no' }
          - { label: 'Danish', value: 'da' }
          - { label: 'Finnish', value: 'fi' }
          - { label: 'Hungarian', value: 'hu' }
          - { label: 'Czech', value: 'cs' }
          - { label: 'Turkish', value: 'tr' }
          - { label: 'Thai', value: 'th' }
          - { label: 'Arabic', value: 'ar' }
          - { label: 'Hebrew', value: 'he' }
          - { label: 'Greek', value: 'el' }
          - { label: 'Indonesian', value: 'id' }
          - { label: 'Vietnamese', value: 'vi' }
          - { label: 'Romanian', value: 'ro' }
          - { label: 'Bulgarian', value: 'bg' }
          - { label: 'Ukrainian', value: 'uk' }
          - { label: 'Malay', value: 'ms' }
          - { label: 'Croatian', value: 'hr' }
          - { label: 'Slovak', value: 'sk' }
          - { label: 'Slovenian', value: 'sl' }
          - { label: 'Estonian', value: 'et' }
          - { label: 'Latvian', value: 'lv' }
          - { label: 'Lithuanian', value: 'lt' }
          - { label: 'Serbian', value: 'sr' }
          - { label: 'Tagalog', value: 'tl' }
          - { label: 'Icelandic', value: 'is' }
          - { label: 'Irish', value: 'ga' }
          - { label: 'Albanian', value: 'sq' }
          - { label: 'Bosnian', value: 'bs' }
          - { label: 'Macedonian', value: 'mk' }
          - { label: 'Maltese', value: 'mt' }
          - { label: 'Welsh', value: 'cy' }
          - { label: 'Belarusian', value: 'be' }
  - name: community-events
    label: Community Events
    label_singular: Community Event
    folder: src/collections/community-events
    slug: '{{title}}'
    create: true
    view_filters:
      - label: Beat Saber Modding Group
        field: host
        pattern: Beat Saber Modding Group
      - label: Cube Community
        field: host
        pattern: Cube Community
      - label: BeastSaber
        field: host
        pattern: BeastSaber
      - label: Beat Khana
        field: host
        pattern: Beat Khana
      - label: Beat Saber Mapping Server
        field: host
        pattern: Beat Saber Mapping Server
      - label: Beat Saber Mapping Workshop
        field: host
        pattern: Beat Saber Mapping Workshop
      - label: Beat Saber Tourneys
        field: host
        pattern: Beat Saber Tourneys
      - label: Beat Saber University League
        field: host
        pattern: Beat Saber University League
      - label: Beat Saber World Cup
        field: host
        pattern: Beat Saber World Cup
      - label: BeatLeader
        field: host
        pattern: BeatLeader
      - label: Comfy Sabers
        field: host
        pattern: Comfy Sabers
      - label: Student Saber Showdown
        field: host
        pattern: Student Saber Showdown
    sortable_fields: ['host', 'title']
    fields:
      - name: host
        label: Host
        widget: relation
        collection: community-event-hosts
        search_fields: [name]
        value_field: name
        display_fields: [name]
      - name: title
        label: Title
      - name: url
        label: URL
      - name: category
        label: Category
        widget: select
        options:
          - { label: 'Tournament', value: 'tournament' }
          - { label: 'Social', value: 'social' }
          - { label: 'Learning', value: 'learning' }
          - { label: 'Awards', value: 'awards' }
          - { label: 'Generic', value: 'generic' }
          - { label: 'Charity', value: 'charity' }
      - name: startDateTime
        label: Start Date/Time
        widget: datetime
        default:
        format: YYYY-MM-DDTHH:mm:ssZ
      - name: useStartTime
        label: Use Start Time
        widget: boolean
        required: false
        default: false
      - name: endDateTime
        label: End Date/Time
        widget: datetime
        required: false
        default:
        format: YYYY-MM-DDTHH:mm:ssZ
      - name: useEndTime
        label: Use End Time
        widget: boolean
        required: false
        default: false
  - name: community-event-hosts
    label: Community Event Hosts
    folder: src/collections/community-event-hosts
    slug: '{{name}}'
    create: true
    fields:
      - name: name
        label: Name
      - name: url
        label: URL
        widget: string
  - name: people
    label: People
    folder: src/collections/people
    slug: '{{name}}'
    create: true
    fields:
      - name: name
        label: name
      - name: beatsaverId
        label: BeatSaver ID
        hint: "The BeatSaver ID of the user. You can find this one in the URL of the user's page on beatsaver.com which will look like this: https://beatsaver.com/profile/${beatsaverId}. The ID is the last part of the URL."
      - name: bio
        label: Bio
        widget: markdown
        required: false
        hint: A short bio of the user. Only used for authors on posts.
      - name: socialLinks
        label: Social Links
        widget: list
        multiple: true
        required: false
        hint: The social links of the user. Only used for authors on posts. The BeatSaver ID is given above as well, but if you want this to be listed as your social links you need to re-enter it here.
        summary: '{{fields.platform}}: {{fields.id}}'
        fields:
          - name: platform
            label: Platform
            widget: select
            options:
              [
                'Discord',
                'Twitter/X',
                'Facebook',
                'Instagram',
                'Twitch',
                'YouTube',
                'Reddit',
                'GitHub',
                'Website',
                'Documentation',
                'BeatSaver',
              ]
          - name: id
            label: ID
            widget: string
  - name: featured-playlist-overwrites
    label: Featured Playlist Overwrites
    folder: src/collections/featured-playlist-overwrites
    slug: '{{id}}'
    create: true
    fields:
      - name: id
        label: BeatSaver Playlist ID
      - name: linkOverwrite
        label: Link Overwrite
        required: false
        hint: If you want to direct the playlist link to a different location than the BeatSaver playlist page write down the URL here. You should start it with "/" if you intend to put a BeastSaber site.
        widget: string
media_folder: 'static/uploads'
public_folder: '/uploads'
